service:
  name: todo

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10

functions:
  # Example without LAMBDA-PROXY integration
  # Invoking locally:
  # sls webpack invoke -f probot
  todo:
    handler: app.probotHandler

    environment:
      WEBHOOK_SECRET: d#Epeu~gpKbV4N3=iQq8&Wtn
      APP_ID: 5739

    events:
     - http:
        path: todo
        method: post
