service:
  name: todo

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10

custom:
  webpackIncludeModules:
    forceInclude:
      - probot
      - fs

functions:
  # Example without LAMBDA-PROXY integration
  # Invoking locally:
  # sls webpack invoke -f probot
  todo:
    handler: handler.todo

    environment:
      WEBHOOK_SECRET: nS8b7hXj2!Mj#uPbs~}KcVVg
      APP_ID: 5739

    events:
     - http:
        path: todo
        method: post
