service:
  name: todo

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  stage: production
  timeout: 10
  runtime: nodejs6.10

custom:
  webpackIncludeModules:
    forceInclude:
      - probot
      - fs

functions:
  todo:
    handler: handler.todo

    environment:
      WEBHOOK_SECRET: ${file(./serverless.env.yml):WEBHOOK_SECRET}
      APP_ID: ${file(./serverless.env.yml):APP_ID}

    events:
     - http:
        path: probot
        method: post
